FROM mcr.microsoft.com/devcontainers/universal:2-linux

#install common dependencies
RUN apt-get update && apt-get install -y python3 python3-pip xz-utils && / apt-get clean && rm - rf /var/lib/apt/lists/*

#installs vue and cli
RUN npm install -g @vue/cli

#installs flask using pip
RUN pip3 install flask

#sets up a working directory
WORKDIR /workspace